//export const ROOT_URL    = 'https://surveyapi.appivly.com/';
export const ROOT_URL    = 'http://192.168.0.118/CUS/lotus/public/api';

export const FETCH_REGEX_STRING = 'FETCH_REGEX_STRING';

export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS';
export const REGISTER_SELLER_FAILURE = 'REGISTER_SELLER_FAILURE';

/*LOGIN*/
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';
/*LOGIN*/

/*SELLMYCAR*/
export const LASTPOSTEDCAR_SUCCESS ='LASTPOSTEDCAR_SUCCESS';
export const LASTPOSTEDCAR_FAILURE ='LASTPOSTEDCAR_FAILURE';
export const SPECIFICATION_SUCCESS ='SPECIFICATION_SUCCESS';
export const SPECIFICATION_FAILURE ='SPECIFICATION_FAILURE';
export const ADD_SPECIFICATION_SUCCESS ='ADD_SPECIFICATION_SUCCESS';
export const ADD_SPECIFICATION_FAILURE ='ADD_SPECIFICATION_FAILURE';
export const ADD_CARIMAGE_SUCCESS = 'ADD_CARIMAGE_SUCCESS';
export const ADD_CARIMAGE_FAILURE = 'ADD_CARIMAGE_FAILURE';
/*SELLMYCAR*/

/* VIEW CMS DETAIL PAGE */
export const VIEW_CMS_DETAIL ='VIEW_CMS_DETAIL';
export const VIEW_CMS_DETAIL_FAILURE ='VIEW_CMS_DETAIL_FAILURE';

export const SEARCH_CAR_LIST ='SEARCH_CAR_LIST';
export const SEARCH_CAR_LIST_FAILURE ='SEARCH_CAR_LIST_FAILURE';

export const FETCH_MAKE_LIST ='FETCH_MAKE_LIST';
export const FETCH_MAKE_LIST_FAILURE ='FETCH_MAKE_LIST_FAILURE';

export const FETCH_MODEL_LIST ='FETCH_MODEL_LIST';
export const FETCH_MODEL_LIST_FAILURE ='FETCH_MODEL_LIST_FAILURE';

export const CAR_TYPE = {"1": "Automatic", "2": "Manual"};
export const FUEL_TYPE = {"1": "Petrol", "2": "Diesel","3":"Hybrid","4":"Electric"};