//export const ROOT_URL    = 'https://surveyapi.appivly.com/';
//export const ROOT_URL    = 'http://111.93.221.222/lotus_api/public/api';
export const ROOT_URL    = 'https://www.perceptionsystem.com/lapi/lotus/public/api';

export const FETCH_REGEX_STRING = 'FETCH_REGEX_STRING';

export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS';
export const REGISTER_SELLER_FAILURE = 'REGISTER_SELLER_FAILURE';

/*LOGIN*/
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';
/*LOGIN*/

/*SELLMYCAR*/
export const LASTPOSTEDCAR_SUCCESS ='LASTPOSTEDCAR_SUCCESS';
export const LASTPOSTEDCAR_FAILURE ='LASTPOSTEDCAR_FAILURE';
export const SPECIFICATION_SUCCESS ='SPECIFICATION_SUCCESS';
export const SPECIFICATION_FAILURE ='SPECIFICATION_FAILURE';
export const ADD_SPECIFICATION_SUCCESS ='ADD_SPECIFICATION_SUCCESS';
export const ADD_SPECIFICATION_FAILURE ='ADD_SPECIFICATION_FAILURE';
export const ADD_CARIMAGE_SUCCESS = 'ADD_CARIMAGE_SUCCESS';
export const ADD_CARIMAGE_FAILURE = 'ADD_CARIMAGE_FAILURE';
export const SELLMYCAR_SUCCESS = 'SELLMYCAR_SUCCESS';
export const SELLMYCAR_FAILURE = 'SELLMYCAR_FAILURE';
//export const STORAGE_URL = 'http://111.93.221.222/lotus_api/storage/app/';
export const STORAGE_URL = 'https://www.perceptionsystem.com/lapi/lotus/storage/app/';
/*SELLMYCAR*/

/* VIEW CMS DETAIL PAGE */
export const VIEW_CMS_DETAIL ='VIEW_CMS_DETAIL';
export const VIEW_CMS_DETAIL_FAILURE ='VIEW_CMS_DETAIL_FAILURE';

export const SEARCH_CAR_LIST ='SEARCH_CAR_LIST';
export const SEARCH_CAR_LIST_FAILURE ='SEARCH_CAR_LIST_FAILURE';

export const FETCH_MAKE_LIST ='FETCH_MAKE_LIST';
export const FETCH_MAKE_LIST_FAILURE ='FETCH_MAKE_LIST_FAILURE';

export const FETCH_MODEL_LIST ='FETCH_MODEL_LIST';
export const FETCH_MODEL_LIST_FAILURE ='FETCH_MODEL_LIST_FAILURE';


export const FETCH_CAR_DETAIL ='FETCH_CAR_DETAIL';
export const FETCH_CAR_DETAIL_FAILURE ='FETCH_CAR_DETAIL_FAILURE';

export const ADD_OFFER ='ADD_OFFER';
export const ADD_OFFER_FAILURE ='ADD_OFFER_FAILURE';

export const EDIT_OFFER ='EDIT_OFFER';
export const EDIT_OFFER_FAILURE ='EDIT_OFFER_FAILURE';


export const REGISTER_DEALER_SUCCESS = 'REGISTER_DEALER_SUCCESS';
export const REGISTER_DEALER_FAILURE = 'REGISTER_DEALER_FAILURE';

export const LIVE_OFFERS_SUCCESS = 'LIVE_OFFERS_SUCCESS';
export const LIVE_OFFERS_FAILURE = 'LIVE_OFFERS_FAILURE';


export const FETCH_OFFER_DETAIL = 'FETCH_OFFER_DETAIL';
export const FETCH_OFFER_DETAIL_FAILURE = 'FETCH_OFFER_DETAIL_FAILURE';


export const PREFERENCE_MODEL_LIST = 'PREFERENCE_MODEL_LIST';
export const PREFERENCE_MODEL_LIST_FAILURE = 'PREFERENCE_MODEL_LIST_FAILURE';

export const SET_PREFERENCE_SUCCESS = 'SET_PREFERENCE_SUCCESS';
export const SET_PREFERENCE_FAILURE = 'SET_PREFERENCE_FAILURE';

export const VIEW_PREFERENCE = 'VIEW_PREFERENCE';
export const VIEW_PREFERENCE_FAILURE = 'VIEW_PREFERENCE_FAILURE';


export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const CAR_TYPE = {"1": "Automatic", "2": "Manual"};
export const FUEL_TYPE = {"1": "Petrol", "2": "Diesel","3":"Hybrid","4":"Electric"};

export const TYRE_LENGTH = ['1','2','3','4','5'];
export const DEALER_TYPE = ["Main Dealer","Independent Dealer","Specialist"];
